name: pomodoro_timer_ui
description: "a Pomodoro Timer App"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.0

dependencies:
  audioplayers: ^6.5.0
  flutter:
    sdk: flutter
  path: ^1.9.1
  path_provider: ^2.1.5
  sqlite3: ^2.9.0
  sqlite3_flutter_libs: ^0.5.39

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/audio/bell.wav
